apiVersion: integration/v1
kind: Step
name: incidents-create
version: 1
summary: Create ServiceNow incident
description: This ServiceNow step container creates an incident.
icon:
build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/servicenow-step-incidents-create

schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs:
    source: file
    file: outputs.schema.json

examples:
  - summary: Create ServiceNow incident
    content:
      apiVersion: v1
      kind: Step
      name: snow-create-incident
      image: relaysh/servicenow-step-incidents-create
      spec:
        servicenow:
          connection: !Connection { type: servicenow, name: my-snow-account }
        description: "My incident"
        shortDescription: "Relay incident"
        priority: '1'
        impact: '1'
        state: '1'
